// <auto-generated />
using System;
using Lumen.Modules.GoogleFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.GoogleFit.Data.Migrations
{
    [DbContext(typeof(GoogleFitContext))]
    partial class GoogleFitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("googlefit")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.GoogleFit.Common.Models.DailyStepsPointInTime", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("Steps")
                        .HasColumnType("bigint");

                    b.HasKey("Date");

                    b.ToTable("DailySteps", "googlefit");
                });

            modelBuilder.Entity("Lumen.Modules.GoogleFit.Common.Models.HourlyStepsPointInTime", b =>
                {
                    b.Property<DateTime>("HourStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Steps")
                        .HasColumnType("bigint");

                    b.HasKey("HourStart");

                    b.ToTable("HourlySteps", "googlefit");
                });
#pragma warning restore 612, 618
        }
    }
}
